### ISSUE TITLE
Fermatas can't be red

### ISSUE THREAD

**Issue by annplaksin** [BirminghamConservatoire/JohannesTinctoris#13]
As it seems, fermatas can't be colored, not even outside of ligatures...
Is this a problem or can we live with it?

![grafik](https://user-images.githubusercontent.com/12529090/87061816-88e00400-c20c-11ea-973e-c1cb5bf2bed3.png)
```
<piece: {mensural: void}, {staf: 5, black}> 
<part: 1>
{clef: C10} {solm: 0} {mens: O5} <lig>BD BB BF {red}*</lig> BD BB BF{red}* BD BB BF{red}?
</part>
</piece>
```

**Comment by JohannesTinctoris** [comment]
Tinctoris used red signa congruentiae consistently in his treatises, so that's why they've been implemented. But the only fermatas throughout the treatises, in *De punctis* xviii.ex1, are black, and of course all the sources of practical music are as well. So we don't have any need for red fermatas. You're off the hook for this one!

Best,
Jeff

----------------------------------------------------------------
 Dr Jeffrey J. Dean          PI, AHRC Mensural Notation Project
 4 Chandos Road                  Royal Birmingham Conservatoire
 Chorlton-cum-Hardy                     tel: +44(0)161 861 7542
 Manchester  M21 0ST                    fax: +44(0)161 861 7543
 England                    www.earlymusictheory.org/Tinctoris/
 jeffrey.dean@bcu.ac.uk         jeffrey.dean@stingrayoffice.com
================================================================

**Comment by annplaksin** [comment]
Good to know! I'll close that one directly
